config/routes.rb
Application.routes.draw do

  resources :tasks
  resources :task_runs
  resources :task_run_sets
  resources :entity_mappings
  resources :entities
  resources :settings
  resources :projects
  resources :report_templates

  match "/" => "welcome#index"  
  root :to => "welcome#index"

  match "/run_task" => "task_run_sets#run", :via => [:post, :get]

  match '/projects/:id/activate', :controller => 'projects', :action => 'activate'

  devise_for :users
  
  mount Resque::Server, :at => "/resque"

end

app/controllers/entity_mappings_controller.rb
class EntityMappingsController < ApplicationController

  before_filter :authenticate_user!

  # GET /entity_mappings
  # GET /entity_mappings.json
  def index
    @entity_mappings = EntityMapping.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entity_mappings }
    end
  end

  # GET /entity_mappings/1
  # GET /entity_mappings/1.json
  def show
    @entity_mapping = EntityMapping.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entity_mapping }
    end
  end

  # GET /entity_mappings/new
  # GET /entity_mappings/new.json
  def new
    @entity_mapping = EntityMapping.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entity_mapping }
    end
  end

  # GET /entity_mappings/1/edit
  def edit
    @entity_mapping = EntityMapping.find(params[:id])
  end

  # POST /entity_mappings
  # POST /entity_mappings.json
  def create
    @entity_mapping = EntityMapping.new(params[:tapir_entity_mapping])

    respond_to do |format|
      if @entity_mapping.save
        format.html { redirect_to @entity_mapping, notice: 'Entity mapping was successfully created.' }
        format.json { render json: @entity_mapping, status: :created, location: @entity_mapping }
      else
        format.html { render action: "new" }
        format.json { render json: @entity_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entity_mappings/1
  # PUT /entity_mappings/1.json
  def update
    @entity_mapping = EntityMapping.find(params[:id])

    respond_to do |format|
      if @entity_mapping.update_attributes(params[:tapir_entity_mapping])
        format.html { redirect_to @entity_mapping, notice: 'Entity mapping was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @entity_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entity_mappings/1
  # DELETE /entity_mappings/1.json
  def destroy
    @entity_mapping = EntityMapping.find(params[:id])
    @entity_mapping.destroy

    respond_to do |format|
      format.html { redirect_to entity_mappings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/entity_mappings_helper.rb
module EntityMappingsHelper
end

app/views/entity_mappings/_form.html.erb
<%= form_for(@entity_mapping) do |f| %>
  <% if @entity_mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity_mapping.errors.count, "error") %> prohibited this entity_mapping from being saved:</h2>

      <ul>
      <% @entity_mapping.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :child_id %><br />
    <%= f.number_field :child_id %>
  </div>
  <div class="field">
    <%= f.label :child_type %><br />
    <%= f.text_field :child_type %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :parent_type %><br />
    <%= f.text_field :parent_type %>
  </div>
  <div class="field">
    <%= f.label :task_run_id %><br />
    <%= f.number_field :task_run_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entity_mappings/index.html.erb
<h1>Listing entity_mappings</h1>

<table>
  <tr>
    <th>Child</th>
    <th>Child type</th>
    <th>Parent</th>
    <th>Parent type</th>
    <th>Task run</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entity_mappings.each do |entity_mapping| %>
  <tr>
    <td><%= entity_mapping.child_id %></td>
    <td><%= entity_mapping.child_type %></td>
    <td><%= entity_mapping.parent_id %></td>
    <td><%= entity_mapping.parent_type %></td>
    <td><%= entity_mapping.task_run_id %></td>
    <td><%= link_to 'Show', entity_mapping %></td>
    <td><%= link_to 'Edit', edit_entity_mapping_path(entity_mapping) %></td>
    <td><%= link_to 'Destroy', entity_mapping, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entity mapping', new_entity_mapping_path %>

app/views/entity_mappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Parent:</b>
  <%= link_to @entity_mapping.get_parent, @entity_mapping.get_parent %>
</p>

<p>
  <b>Child:</b>
  <%= link_to @entity_mapping.get_child, @entity_mapping.get_child %>
</p>

<p>
  <b>Task run:</b>
  <%= link_to TaskRun.where(:id => @entity_mapping.task_run_id).first %>
</p>


<%= link_to 'Edit', edit_entity_mapping_path(@entity_mapping) %> |
<%= link_to "Destroy", @entity_mapping, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back', entity_mappings_path %>