config/routes.rb
Application.routes.draw do

  resources :tasks
  resources :task_runs
  resources :task_run_sets
  resources :entity_mappings
  resources :entities
  resources :settings
  resources :projects
  resources :report_templates

  match "/" => "welcome#index"  
  root :to => "welcome#index"

  match "/run_task" => "task_run_sets#run", :via => [:post, :get]

  match '/projects/:id/activate', :controller => 'projects', :action => 'activate'

  devise_for :users
  
  mount Resque::Server, :at => "/resque"

end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController

  before_filter :authenticate_user!

  # GET /entities
  # GET /entities.json
  def index

    session["view_types"] = params["type"] if params["type"]
    entities = []
    session["view_types"].each do |type|

      if Entities.const_defined? type
        entities << eval("Entities::#{type}").all 
      end
    end

    # Gather all tasks for our task runner
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: EntitiesDatatable.new(view_context, entities) }
    end
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
    @entity = Entities::Base.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entity }
    end
  end

  # GET /entities/new
  # GET /entities/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entity }
    end
  end

  # GET /entities/1/edit
  def edit
    @entity = Entities::Base.find(params[:id])
  end

  # POST /entities
  # POST /entities.json
  def create

    # interpret the type based on the user's input. 
    type = params[:type]
    
    # TODO - there has to be a better way to do this
    render action: "new", notice: "invalid entity type." unless get_valid_type_class_names.include?(type)

    @entity = eval("Entities::#{type}").create

    respond_to do |format|
      if @entity.save(:validate => false)
        format.html { render action: "edit", notice: 'entity was successfully created.' }
        format.json { render json: @entity, status: :created, location: @entity }
      else
        format.html { render action: "new", notice: "unable to save entity." }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entities/1
  # PUT /entities/1.json
  def update
    @entity = Entities::Base.find(params[:oid])

    respond_to do |format|
      if @entity.update_attributes(params)
        format.html { redirect_to entity_path(@entity), notice: 'Entity was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity = Entities::Base.find(params[:id])
    @entity.destroy

    respond_to do |format|
      format.html { 
        # This is a hack to handle the delete via the 
        # task_run_sets page specially. We don't want 
        # to always send the user back to the index action
        if request.referer =~ /task_run_sets/
          redirect_to request.referer
        else
          redirect_to entities_url 
        end
      }
      format.json { head :ok }
    end
  end



  
  # Return the valid entity types
  def get_valid_type_class_names
    types = Entities::Base.descendants.map{|x| x.name.split("::").last}
  types.sort_by{ |t| t.downcase }
  end

  private  
    # Return the valid entity types
    def _get_valid_types
      types = Entities::Base.descendants
    end

end

app/helpers/entities_helper.rb
module EntitiesHelper

  ### TODO - There's probably a better way to do this
  ### even if it means using method_missing

  def entities_account_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_doc_file_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_dns_record_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_email_address_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_finding_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_facebook_account_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_host_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_image_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_klout_account_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_linkedin_account_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_net_block_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_net_svc_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_note_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_organization_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_parsable_file_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_pdf_file_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_phone_number(id=nil)
    "/entities/#{id}"  
  end

  def entities_physical_location_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_search_result_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_search_string_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_person_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_twitter_account_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_username_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_web_application_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_web_page_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_web_form_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_web_reference_path(id=nil)
    "/entities/#{id}"  
  end

  def entities_xls_file_path(id=nil)
    "/entities/#{id}"  
  end

end

app/views/entities/_display.html.erb
<div class="fields">
  <!-- Iterate through fields here --> 
  <table>
  <% @entity.fields.each do |field,value|
      next if field =~ /_id|created_at|updated_at|status|age|confidence/ %>
    <tr>
      <% # Check to make sure it's not an empty value first
         unless eval("@entity.#{value.name}") == "" %>
        <td><%= value.name %>:</td>      
        <td>
          <%= if value.name == "text"
               simple_format "#{eval("@entity.#{value.name}")}" unless eval("@entity.#{value.name}") == ""
              elsif value.name == "uri"
                simple_format "<a href=\"#{eval("@entity.#{value.name}")}\" target=\"_blank\">#{eval("@entity.#{value.name}")}</a>"
              else
                "#{eval("@entity.#{value.name}")}" unless eval("@entity.#{value.name}") == "" 
              end
          %>
        </td>
      <% end %>
    </tr>
  <% end %>

  <% if @entity.kind_of?(Entities::LocalImage) %>
      <tr><td>Image:</td><td><img src="/images/<%=@entity.name.split("/").last%>"/></td><tr>
  <% end %>

  <% if @entity.kind_of?(Entities::RemoteImage) %>
      <tr><td>Image:</td><td><img src="<%=@entity.name%>"/></td><tr>
  <% end %>

  <% if @entity.kind_of?(Entities::PhysicalLocation) %>
      <tr>
        <td>Image:</td>
        <td><img src="http://maps.googleapis.com/maps/api/staticmap?center=<%=@entity.latitude%>,<%=@entity.longitude%>&zoom=11&size=200x200&sensor=false"></td>
      </tr>
      <tr>
        <td>Street View:</td>
        <td><img src="http://maps.googleapis.com/maps/api/streetview?size=200x200&location=<%=@entity.latitude%>,<%=@entity.longitude%>&heading=0&sensor=true"></td>
        <td><img src="http://maps.googleapis.com/maps/api/streetview?size=200x200&location=<%=@entity.latitude%>,<%=@entity.longitude%>&heading=90&sensor=true"></td>
        <td><img src="http://maps.googleapis.com/maps/api/streetview?size=200x200&location=<%=@entity.latitude%>,<%=@entity.longitude%>&heading=180&sensor=true"></td>
        <td><img src="http://maps.googleapis.com/maps/api/streetview?size=200x200&location=<%=@entity.latitude%>,<%=@entity.longitude%>&heading=270&sensor=true"></td>
      </tr>
  <% end %>

  </table>
  <!-- Done iterating through fields --> 
</div>

app/views/entities/_form.html.erb
<%= 
form_for(@entity, :url => "/entities/#{@entity.id}") do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="fields">

    <input type="hidden" name="oid" value="<%= @entity.id %>"></input>
    <input type="hidden" name="type" value="<%= @entity._type %>"></input>

    <!-- Iterate through fields here --> 
    <table>
    <% @entity.fields.each do |field,value|
        next if field =~ /_type|_id|age|created_at|updated_at|confidence|status/ %>
        <tr>
          <td><%= label_tag value.name %></td>
          <td><%= text_field_tag value.name, eval("@entity.#{value.name}") %> </td>
        </tr>
    <% end %>
    </table>
    <!-- Done iterating through fields --> 
  </div>
  <br/>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/entities/_task_runner.erb
<p>
<% if @entity.tasks.count > 0 %>
  <b>Run Task:</b>
  <form name="task_runner" id="run_task" action="/run_task" method="POST"> 
    <%=token_tag form_authenticity_token %>
    <input type="hidden" type="checkbox" name="entities[<%="#{@entity._type}##{@entity.id}"%>]" value="checked"></input>
    <select name="task_name">
    <% @entity.tasks.each do |t| %>
      <option value="<%=t.name%>"><%=t%></option>
    <% end %>
    </select>
    <input type="Submit" value="Run Task"></input>
  </form>
<% else %>
  <b>Run Task:</b>
  No tasks.
<% end %>
</p>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>
<br/>
<%= render 'form' %>
<%= link_to 'Back', entities_path %>

app/views/entities/index.html.erb
<table id="entities" class="display" data-source="<%= entities_url(format: "json") %>">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/entities/new.html.erb
<h1>New entity</h1>

<%= form_tag entities_path do %>
  <%= select_tag "type", options_from_collection_for_select(get_valid_type_class_names, "to_s", "to_s") %>
  <%= submit_tag "Create" %>
<% end %>

<%= link_to 'Back', entities_path %>

app/views/entities/show.html.erb
<p>
<%= render 'display' %>
</p>

<%= render 'task_runner' %>

<p>
<b>Parent Entities:</b>
  <%= simple_format render_parents(@entity) %>
</p>  

<p>
<b>Children Entities:</b>
  <%= simple_format render_children(@entity) %>
</p>

<p>
<b>Task Runs that found this entity:</b>
  <ul>
  <% @entity.parent_task_runs.each {|r|%>
    <li><%= link_to r, task_run_path(r)  %></li>
  <% } %>
  </ul>
</p>

<p>
<b>Task Runs on this entity:</b>
  <ul>
  <% @entity.task_runs.each {|r|%>
    <li><%= link_to r, task_run_path(r)  %></li>
  <% } %>
  </ul>
</p>

<%= link_to "Destroy", entity_path(@entity), :confirm => 'Are you sure?', :method => :delete %>| 
<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>