config/routes.rb
Application.routes.draw do

  resources :tasks
  resources :task_runs
  resources :task_run_sets
  resources :entity_mappings
  resources :entities
  resources :settings
  resources :projects
  resources :report_templates

  match "/" => "welcome#index"  
  root :to => "welcome#index"

  match "/run_task" => "task_run_sets#run", :via => [:post, :get]

  match '/projects/:id/activate', :controller => 'projects', :action => 'activate'

  devise_for :users
  
  mount Resque::Server, :at => "/resque"

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_filter :authenticate_user!

  # GET /settings
  # GET /settings.json
  def index
    
    # HACKY!!!
    current_user.create_settings

    @settings = Setting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settings }
    end
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
    @setting = Setting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/new
  # GET /settings/new.json
  def new
    @setting = Setting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/1/edit
  def edit
    @setting = Setting.find(params[:id])
  end

  # POST /settings
  # POST /settings.json
  def create

    @setting = Setting.new(
      :tenant => Tenant.current,
      :user => current_user,
      :name => params[:name],
      :value => params[:value])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to "/settings/#{@setting.id}", notice: 'Setting was successfully created.' }
        format.json { render json: @setting, status: :created, location: @setting }
      else
        format.html { render action: "new" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /settings/1
  # PUT /settings/1.json
  def update
    @setting = Setting.find(params[:oid])

    #binding.pry

    respond_to do |format|
      if @setting.update_attributes(params)
        format.html { redirect_to  "/settings/#{@setting.id}", notice: 'Setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_display.html.erb
<div class="fields">
  <!-- Iterate through fields here --> 
  <table>
  <% @setting.fields.each do |key,value|
    next if key =~ /_type|_id|status/ %>
    <tr>
      <td><%= value.name %>:</td>
      <td><%= eval("@setting.#{value.name}")%></td>
    </tr>
  <% end %>
  </table>
  <!-- Done iterating through fields --> 
</div>

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fields">

    <input type="hidden" name="oid" value="<%= @setting.id %>"></input>
    <input type="hidden" name="type" value="<%= @setting._type %>"></input>

    <!-- Iterate through fields here --> 
    <table>
    <% @setting.fields.each do |field,value|
        next if field =~ /_type|_id|created_at|updated_at|status|visibility/ %>
      <tr>
        <td><%= value.name %>:</td>
        <td><input name="<%=value.name%>" type="string" value=<%= eval("@setting.#{value.name}")%> > </input></td>
      </tr>
    <% end %>
    </table>
    <!-- Done iterating through fields --> 
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h1>Listing settings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @settings.each do |setting| %>
  <tr>
    <td><%= setting.name %></td>
    <td><%= setting.value %></td>
    <td><%= link_to 'Show', setting %></td>
    <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
    <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render 'form' %>

<%= link_to 'Back', tapir_settings_path %>

app/views/settings/show.html.erb
<p>
  <%= render 'display' %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Destroy', @setting, method: :delete, data: { confirm: 'Are you sure?' } %>|
<%= link_to 'Back', settings_path %>