config/routes.rb
Application.routes.draw do

  resources :tasks
  resources :task_runs
  resources :task_run_sets
  resources :entity_mappings
  resources :entities
  resources :settings
  resources :projects
  resources :report_templates

  match "/" => "welcome#index"  
  root :to => "welcome#index"

  match "/run_task" => "task_run_sets#run", :via => [:post, :get]

  match '/projects/:id/activate', :controller => 'projects', :action => 'activate'

  devise_for :users
  
  mount Resque::Server, :at => "/resque"

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entity_mapping }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects
  def create

    @project = Project.new({
        :tenant => Tenant.current}.merge(params[:project]))

    respond_to do |format|
      if @project.save
       
        # Set a cookie so it's activated 
        cookies.permanent[:project] = @project.name
       
        Project.current = @project

        # Create an initial search string
        e = Entities::SearchString.create(:name => @project.name)

        # Let the user know
        flash[:notice] = "Project created and activated!"
       
        # Respond
        format.html { redirect_to entities_path, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new", notice: "Unable to save project." }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to project_path(@project), notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "show" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def activate
    @project = Project.find(params[:id])
    
    # Destroy all associated entites
    cookies.permanent[:project] = @project.name

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    
    # Destroy all associated entites
    @project_entities = Entities::Base.all.each { |entity| entity.destroy  }

    # Destroy the project
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end



end

app/helpers/project_helper.rb
module ProjectHelper
  
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<table border=1>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Entities</th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <% if project == Project.current %>
      <td><b><%= link_to project.name, project_path(project) %></b></td>
    <% else %>
      <td><%= link_to project.name, project_path(project) %></td>
    <% end %>
    <td><%= project.description %></td>
    <td><%= Entities::Base.where(:project_id => project.id).count %></td>

  </tr>
<% end %>
</table>

<br /><br />
<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<p>
<b>Name:</b>
  <%= @project.name %>
</p>  

<p>
<b>Description:</b>
  <%= @project.description %>
</p>

<% if cookies[:project] == @project.name %>
  Activate | 
<% else %>
  <%= link_to("Activate", "#{project_path(@project)}/activate", :method => :activate) %> |
<% end %>
<%= link_to "Destroy", project_path(@project), :confirm => 'Are you sure you want to delete this project?', :method => :delete %>| 
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>